name: RegenPlugin
main: com.gmail.ddmytriw.RegenPlugin.RegenPlugin
version: 0.1

commands:
   regen:
      description: Regen mod start or stop.
      usage: /regen <start/stop>
      permission: MinecraftTestPlugin.testplugin
      permission-message: You don't have <permission>